set (BOARD_USE_MCX512		OFF	CACHE BOOL "")
set (BOARD_USE_MCX514		OFF	CACHE BOOL "")
set (BOARD_USE_PCD4641		OFF	CACHE BOOL "")
set (BOARD_USE_INTERNAL_SPI	ON	CACHE BOOL "")
set (BOARD_USE_DAC124S085	ON	CACHE BOOL "")



