
if (TARGET_RX_USER_BOOT_IMAGE)
  add_global_toolchain_definitions (-DRX_USER_BOOT_IMAGE)
  set (TARGET_ROM_END "0xFF7FFFFF" CACHE STRING "ROM end address")
else ()
  set (TARGET_ROM_END "0xFFFFFFFF" CACHE STRING "ROM end address")
endif ()

set (TARGET_RAM_START "0x00000100" CACHE STRING "RAM start address")
set (TARGET_ISTACK_SIZE "1024" CACHE STRING "istack size in bytes")
set (TARGET_USTACK_SIZE "1024*2" CACHE STRING "ustack size in bytes")

option (TARGET_RX_USER_BOOT_IMAGE "build a user boot image" OFF)
option (TARGET_RX_TEXT_IN_RAM "the .text section is located in RAM instead of ROM" OFF)

set (BOARD_TYPE_ID "MCB2" CACHE STRING "Board Type ID")
add_global_toolchain_definitions (-DBOARD_TYPE_ID_MCB2)

set (BOARD_VARIANT "RX63N_144" CACHE STRING "Board Variant")
set_property (CACHE BOARD_VARIANT PROPERTY STRINGS RX631_144 RX63N_144 RX64M_144 RX71M_144 RX64M_176 RX71M_176)

if (TARGET_RX_TEXT_IN_RAM)
  add_global_toolchain_definitions (-DRX_TEXT_IN_RAM)
endif ()

if (${BOARD_VARIANT} STREQUAL "RX631_144")
  add_global_toolchain_definitions (-DMCB_USE_RX631_144)
  add_global_toolchain_definitions (-DMCB_USE_RX63)
  if (TARGET_RX_USER_BOOT_IMAGE)
    set (TARGET_ROM_SIZE "1024*16" CACHE STRING "ROM size in bytes")
  else ()
    set (TARGET_ROM_SIZE "1024*256" CACHE STRING "ROM size in bytes")
  endif ()
  set (TARGET_RAM_SIZE "1024*128-256" CACHE STRING "RAM size in bytes")
  set (TARGET_CPU "RX600" CACHE STRING "CPU Type")

elseif (${BOARD_VARIANT} STREQUAL "RX63N_144")
  add_global_toolchain_definitions (-DMCB_USE_RX63N_144)
  add_global_toolchain_definitions (-DMCB_USE_RX63)
  if (TARGET_RX_USER_BOOT_IMAGE)
    set (TARGET_ROM_SIZE "1024*16" CACHE STRING "ROM size in bytes")
  else ()
    set (TARGET_ROM_SIZE "1024*768" CACHE STRING "ROM size in bytes")
  endif ()
  set (TARGET_RAM_SIZE "1024*128-256" CACHE STRING "RAM size in bytes")
  set (TARGET_CPU "RX600" CACHE STRING "CPU Type")

elseif (${BOARD_VARIANT} STREQUAL "RX64M_144")
  add_global_toolchain_definitions (-DMCB_USE_RX64M_144)
  add_global_toolchain_definitions (-DMCB_USE_RX64)
  add_global_toolchain_definitions (-DMCB_USE_RX64_RX71)
  if (TARGET_RX_USER_BOOT_IMAGE)
    set (TARGET_ROM_SIZE "1024*32" CACHE STRING "ROM size in bytes")
  else ()
    set (TARGET_ROM_SIZE "1024*1024*2" CACHE STRING "ROM size in bytes")
  endif ()
  set (TARGET_RAM_SIZE "1024*512-256" CACHE STRING "RAM size in bytes")
  set (TARGET_CPU "RXv2" CACHE STRING "CPU Type")

elseif (${BOARD_VARIANT} STREQUAL "RX71M_144")
  add_global_toolchain_definitions (-DMCB_USE_RX71M_144)
  add_global_toolchain_definitions (-DMCB_USE_RX71)
  add_global_toolchain_definitions (-DMCB_USE_RX64_RX71)
  if (TARGET_RX_USER_BOOT_IMAGE)
    set (TARGET_ROM_SIZE "1024*32" CACHE STRING "ROM size in bytes")
  else ()
    set (TARGET_ROM_SIZE "1024*1024*2" CACHE STRING "ROM size in bytes")
  endif ()
  set (TARGET_RAM_SIZE "1024*512-256" CACHE STRING "RAM size in bytes")
  set (TARGET_CPU "RXv2" CACHE STRING "CPU Type")

elseif (${BOARD_VARIANT} STREQUAL "RX64M_176")
  add_global_toolchain_definitions (-DMCB_USE_RX64M_176)
  add_global_toolchain_definitions (-DMCB_USE_RX64)
  add_global_toolchain_definitions (-DMCB_USE_RX64_RX71)
  if (TARGET_RX_USER_BOOT_IMAGE)
    set (TARGET_ROM_SIZE "1024*32" CACHE STRING "ROM size in bytes")
  else ()
    set (TARGET_ROM_SIZE "1024*1024*2" CACHE STRING "ROM size in bytes")
  endif ()
  set (TARGET_RAM_SIZE "1024*512-256" CACHE STRING "RAM size in bytes")
  set (TARGET_CPU "RXv2" CACHE STRING "CPU Type")

elseif (${BOARD_VARIANT} STREQUAL "RX71M_176")
  add_global_toolchain_definitions (-DMCB_USE_RX71M_176)
  add_global_toolchain_definitions (-DMCB_USE_RX71)
  add_global_toolchain_definitions (-DMCB_USE_RX64_RX71)
  if (TARGET_RX_USER_BOOT_IMAGE)
    set (TARGET_ROM_SIZE "1024*32" CACHE STRING "ROM size in bytes")
  else ()
    set (TARGET_ROM_SIZE "1024*1024*2" CACHE STRING "ROM size in bytes")
  endif ()
  set (TARGET_RAM_SIZE "1024*512-256" CACHE STRING "RAM size in bytes")
  set (TARGET_CPU "RXv2" CACHE STRING "CPU Type")

else ()
  message (FATAL_ERROR "undefined board variant")

endif ()

option (BOARD_USE_INTERNAL_SPI "Enable on-board internal SPI on SCI4" OFF)
option (BOARD_USE_DAC124S085 "Enable the DAC124S085 device" OFF)
option (BOARD_USE_RS485 "Enable RS485 ports" ON)
option (BOARD_USE_CAN "Enable CAN port" ON)
option (BOARD_USE_PCD4641 "Enable the PCD4641 device" ON)
option (BOARD_USE_MCX514 "Enable the MCX514 device" ON)
option (BOARD_USE_MCX512 "Enable the MCX512 device" OFF)
option (BOARD_USE_USB0 "Enable the USB0 function device" OFF)
option (BOARD_USE_USBA "Enable the USBA host device" OFF)
option (BOARD_USE_TRIGGER_IO "Enable the trigger IO device" ON)
option (BOARD_USE_LEDS "Enable the LED outputs device" ON)
option (BOARD_USE_DIPSWITCH "Enable the dipswitch inputs device" ON)
option (BOARD_USE_DIGITAL_IO "Enable the digital IO device" ON)
option (BOARD_USE_EMG_STOP "Enable EMG stop digital input" ON)
option (BOARD_USE_ETHERC0 "Enable the RX EtherC device as eth0" ON)
option (BOARD_USE_ETHERC0_RAW "Enable the RX EtherC device as raw device" OFF)

if (BOARD_VARIANT MATCHES ".*_144")
  option (BOARD_USE_ETHERC1 "Enable the RX EtherC device as eth1" OFF)
else ()
  option (BOARD_USE_ETHERC1 "Enable the RX EtherC device as eth1" ON)
endif ()

option (BOARD_USE_ETHERC1_RAW "Enable the RX EtherC device as raw device" OFF)
option (BOARD_USE_LAN9250 "Enable the LAN9250 device as eth2" OFF)
option (BOARD_USE_LAN9250_RAW "Enable the LAN9250 device as raw device" OFF)
option (BOARD_USE_FCU "Enable the FCU device" ON)
option (BOARD_USE_SCI_DEBUG "Use SCI1 as debug printf output" ON)
option (BOARD_USE_SCI0_USART "Enable general purpose serial port on SCI0" ON)
option (BOARD_USE_SCI2_USART "Enable general purpose serial port on SCI2" ON)
option (BOARD_USE_SCI3_USART "Enable general purpose serial port on SCI3" ON)
option (BOARD_USE_SCI4_USART "Eanble general purpose serial port on SCI4 (shared with internal SPI)" ON)
option (BOARD_USE_SCI5_USART "Enable general purpose serial port on SCI5" ON)
option (BOARD_USE_TPU "Enable the TPU device" ON)

if (NOT BOARD_VARIANT MATCHES "RX63.*")
  option (BOARD_USE_GPT "Enable the GPT device" ON)
endif ()

option (BOARD_USE_DTC "Enable the DTC device" ON)
option (BOARD_USE_DMACA "Enable the DMACA device" ON)
option (BOARD_USE_NAND_FLASH "Enable the NAND flash device" OFF)
option (BOARD_USE_STANDBY_POWER_SUPPLY "Enable the standby power supply" OFF)
option (BOARD_NO_RX_CRC "Do not use RX hardware CRC calculator" OFF)
option (BOARD_NO_RESET_HW_INIT "Do not initialize hardware at reset" OFF)
option (BOARD_NO_PERIPHERAL_RESET_RELEASE "Do not assert or release the peripheral reset line during and after board initialization" OFF)
option (BOARD_INVERTED_BAT_LTEST_EN_BAT_VTEST_EN "Invert BAT_LTEST_and EN_BAT_VTEST_EN output signals for early board revisions" OFF)
option (BOARD_ASSERT_MSG_NO_FUNCNAME "Omit function name from assert message to save space" ON)

if (BOARD_USE_INTERNAL_SPI)
  add_global_toolchain_definitions (-DMCB_USE_SPI)
endif ()

if (BOARD_USE_DAC124S085)
  add_global_toolchain_definitions (-DMCB_USE_DAC124S085)
endif ()

if (BOARD_USE_RS485)
  add_global_toolchain_definitions (-DMCB_USE_RS485)
endif ()

if (BOARD_USE_PCD4641)
  add_global_toolchain_definitions (-DMCB_USE_PCD4641)
endif ()

if (BOARD_USE_MCX514)
  if (BOARD_USE_MCX512)
    message (FATAL_ERROR "can't use MCX514 and MCX512 at the same time")
  endif ()

  add_global_toolchain_definitions (-DMCB_USE_MCX514)
endif ()

if (BOARD_USE_MCX512)
  if (BOARD_USE_MCX514)
    message (FATAL_ERROR "can't use MCX514 and MCX512 at the same time")
  endif ()

  add_global_toolchain_definitions (-DMCB_USE_MCX512)
endif ()

if (BOARD_USE_USB0)
  add_global_toolchain_definitions (-DMCB_USE_USB_FUNCTION)
endif ()

if (BOARD_USE_USBA)
  if (BOARD_VARIANT MATCHES ".*_144")
    message (FATAL_ERROR "USBA not supported with 144 pin MCU")
  endif ()
  add_global_toolchain_definitions (-DMCB_USE_USB_HOST)
endif ()

if (BOARD_USE_TRIGGER_IO)
  add_global_toolchain_definitions (-DMCB_USE_TRIGGER_IO)
endif ()

if (BOARD_USE_LEDS)
  add_global_toolchain_definitions (-DMCB_USE_LEDS)
endif ()

if (BOARD_USE_DIPSWITCH)
  add_global_toolchain_definitions (-DMCB_USE_DIPSWITCH)
endif ()

if (BOARD_USE_DIGITAL_IO)
  add_global_toolchain_definitions (-DMCB_USE_DIGITAL_IO)
endif ()

if (BOARD_USE_EMG_STOP)
  add_global_toolchain_definitions (-DMCB_USE_EMG_STOP)
endif ()

if (BOARD_USE_ETHERC0)
  add_global_toolchain_definitions (-DMCB_USE_RX_ETHERC0)
endif ()

if (BOARD_USE_ETHERC0_RAW)
  add_global_toolchain_definitions (-DMCB_USE_RX_ETHERC0_RAW)
endif ()

if (BOARD_USE_ETHERC1)
  if (BOARD_VARIANT MATCHES ".*_144")
    message (FATAL_ERROR "ETH1 not supported with 144 pin MCU")
  endif ()
  add_global_toolchain_definitions (-DMCB_USE_RX_ETHERC1)
endif ()

if (BOARD_USE_ETHERC1_RAW)
  if (BOARD_VARIANT MATCHES ".*_144")
    message (FATAL_ERROR "ETH1 not supported with 144 pin MCU")
  endif ()
  add_global_toolchain_definitions (-DMCB_USE_RX_ETHERC1_RAW)
endif ()

if (BOARD_USE_LAN9250)
  add_global_toolchain_definitions (-DMCB_USE_LAN9250)
endif ()

if (BOARD_USE_LAN9250_RAW)
  add_global_toolchain_definitions (-DMCB_USE_LAN9250_RAW)
endif ()

if (BOARD_USE_FCU)
  add_global_toolchain_definitions (-DMCB_USE_FCU)
endif ()

if (BOARD_USE_SCI_DEBUG)
  add_global_toolchain_definitions (-DMCB_USE_SCI_DEBUG)
endif ()

if (BOARD_USE_SCI0_USART)
  add_global_toolchain_definitions (-DMCB_USE_SCI0_USART)
endif ()

if (BOARD_USE_SCI3_USART)
  add_global_toolchain_definitions (-DMCB_USE_SCI3_USART)
endif ()

if (BOARD_USE_SCI2_USART)
  add_global_toolchain_definitions (-DMCB_USE_SCI2_USART)
endif ()

if (BOARD_USE_SCI5_USART)
  add_global_toolchain_definitions (-DMCB_USE_SCI5_USART)
endif ()

if (BOARD_USE_TPU)
  add_global_toolchain_definitions (-DMCB_USE_TPU)
endif ()

if (BOARD_USE_GPT)
  if (BOARD_VARIANT MATCHES "RX63.*")
    message (FATAL_ERROR "GPT not supported on RX63 MCU")
  endif ()
  add_global_toolchain_definitions (-DMCB_USE_GPT)
endif ()

if (BOARD_USE_DTC)
  add_global_toolchain_definitions (-DMCB_USE_DTC)
endif ()

if (BOARD_USE_DMACA)
  add_global_toolchain_definitions (-DMCB_USE_DMACA)
endif ()

if (BOARD_USE_NAND_FLASH)
  if (BOARD_VARIANT MATCHES ".*_144")
    message (FATAL_ERROR "NAND flash not supported with 144 pin MCU")
  endif ()
  add_global_toolchain_definitions (-DMCB_USE_NAND_FLASH)
endif ()

if (BOARD_NO_RX_CRC)
  add_global_toolchain_definitions (-DMCB_NO_CRC)
endif ()

if (BOARD_NO_RESET_HW_INIT)
  add_global_toolchain_definitions (-DMCB_NO_RESET_HW_INIT)
endif ()

if (BOARD_NO_PERIPHERAL_RESET_RELEASE)
  add_global_toolchain_definitions (-DMCB_NO_PERIPHERAL_RESET_RELEASE)
endif ()

if (BOARD_USE_STANDBY_POWER_SUPPLY)
  if (BOARD_VARIANT MATCHES ".*_144")
    message (FATAL_ERROR "Standby Power Supply not supported with 144 pin MCU")
  endif ()
  add_global_toolchain_definitions (-DMCB_USE_STANDBY_POWER_SUPPLY)
endif ()

if (BOARD_INVERTED_BAT_LTEST_EN_BAT_VTEST_EN)
  add_global_toolchain_definitions (-DMCB_INVERTED_BAT_LTEST_EN_BAT_VTEST_EN)
endif ()

if (BOARD_ASSERT_MSG_NO_FUNCNAME)
  add_global_toolchain_definitions (-DBOARD_ASSERT_MSG_NO_FUNCNAME)
endif ()
